services:
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    image: sweetcolors-auth-service:latest
    container_name: sweetcolors-auth
    ports:
      - "8081:8081"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECURE: "false"

  catalog-service:
    build:
      context: ./backend/catalog-service
      dockerfile: Dockerfile
    image: sweetcolors-catalog-service:latest
    container_name: sweetcolors-catalog
    ports:
      - "8082:8082"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CATALOG_BASE_URL: http://catalog-service:8082

  wishlist-service:
    build:
      context: ./backend/wishlist-service
      dockerfile: Dockerfile
    image: sweetcolors-wishlist-service:latest
    container_name: sweetcolors-wishlist
    ports:
      - "8083:8083"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      WISHLIST_BASE_URL: http://wishlist-service:8083
      CATALOG_BASE_URL: http://catalog-service:8082

  history-service:
    build:
      context: ./backend/history-service
      dockerfile: Dockerfile
    image: sweetcolors-history-service:latest
    container_name: sweetcolors-history
    ports:
      - "8084:8084"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      HISTORY_BASE_URL: http://history-service:8084

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    image: sweetcolors-api-gateway:latest
    container_name: sweetcolors-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - catalog-service
      - wishlist-service
      - history-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sweetcolors-frontend
    ports:
      - "5500:5500"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - api-gateway